### PR TITLE
Opimize functions by memoizing 🚅

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Memoizing the functions using [`useCallback`](https://reactjs.org/docs/hooks-reference.html#usecallback)

_Sorry if I made any mistakes :(_

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Please remove the formatting changes.

**Comment by sanjaiyan-dev** [comment]
> Please remove the formatting changes.

Done

**Comment by sanjaiyan-dev** [comment]
> Please remove the formatting changes.

Done 🙌💪

**Comment by tannerlinsley** [comment]
This is no longer relevant with TanStack Router

**Pull request closed without merging**
