### PR TITLE
feat(router-devtools): add shadowDOMTarget option to TanStackRouterDevtools and TanStackRouterDevtoolsPanel (#1709)

### LINKED ISSUE #1709: TanStackRouterDevtools broken when rendering inside of a shadow DOM
### Describe the bug

I'm using Tanstack Query and Router inside of a shadow DOM. The Query devtools have a [shadowDOMTarget option](https://tanstack.com/query/latest/docs/framework/react/devtools?from=reactQueryV3#options) that makes it possible to render them correctly. The Router devtools sadly lack such an option which makes them pretty much unusable.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-3rsmfi?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

Just launch the project. The broken devtools are instantly visible as the hiding/showing doesn't work.

### Expected behavior

As a developer, I expect to be able to use the devtools when rendering my React app inside of a shadow DOM.

### Screenshots or Videos

image

### Platform

- OS: Windows
- Browser: Chrome
- Version: 125

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by reihwald**
Closes #1709 

TanStackRouterDevtools before:

Screenshot 2024-06-06 170017

TanStackRouterDevtoolsPanel before:

Screenshot 2024-06-06 165959

TanStackRouterDevtools after:

Screenshot 2024-06-06 163338

TanStackRouterDevtoolsPanel after:

Screenshot 2024-06-06 163356

### CODE REVIEW

**Comment by SeanCassiere** [comment]
This needs to be checked locally to make sure there aren't any visual regressions for the existing (non ShadowDOM) users.

**Comment by ardeora** [comment]
@SeanCassiere  Thanks! I will take a look at this tomorrow 😄  (Saturday)

**Comment by reihwald** [comment]
Should I show you screenshots of the devtools in a no shadow dom setup?

**Review by ardeora — APPROVED** [review]
@SeanCassiere This is looking good! I tested it out with CSR and SSR examples too and the styles are looking to hold up well!

**Comment by ardeora** [comment]
@SeanCassiere Also the devtoolsPanel styles are broken in the existing implementation. I'll try to fix them in a new PR. This isn't related to the shadow dom changes 😄

**Comment by SeanCassiere** [comment]
> @SeanCassiere Also the devtoolsPanel styles are broken in the existing implementation. I'll try to fix them in a new PR. This isn't related to the shadow dom changes 😄 

Is this fine to go through for now?

**Comment by ardeora** [comment]
Yeah all good to go! Thanks @reihwald for working on this!

**Comment by reihwald** [comment]
Glad I could help 👍

**Pull request merged**
