### PR TITLE
feat(router-generator): add a biome-ignore comment on the generated route-tree file

### PR DESCRIPTION
**Pull request by k35o**
Errors do occur in `routeTree.gen.ts` in projects that use biome to check code.
I would like to ignore the errors in the generated files as well as in the response to eslint.

### CODE REVIEW

**Review by SeanCassiere — APPROVED** [review]

**Comment by SeanCassiere** [comment]
@k35o can you please update the test snapshots in `packages/router-generator/tests/generator/**/routeTree.expected.ts` with the new line being added in.

**Comment by k35o** [comment]
@SeanCassiere 
Thank you! I update it!

**Review by SeanCassiere — APPROVED** [review]

**Comment by schiller-manuel** [comment]
instead of adding each possible ignore instruction separately, I would rather add a possibility to let the user customize the header.

**Comment by SeanCassiere** [comment]
@schiller-manuel an array of strings would probably make the most sense.

Also, this change would require the ability to both *prepend* and *append* to the file in that case, since some tools have their comments set up in a way to `pause tracking` and `resume tracking`.

**Comment by SeanCassiere** [comment]
@schiller-manuel PR is up!

https://github.com/TanStack/router/pull/1502

**Comment by SeanCassiere** [comment]
Superseded by #1502.

@k35o thank you for your contribution which led to a user-customizable feature being added in #1502.

You can upgrade the router-generator to version [1.30.0](https://github.com/TanStack/router/releases/tag/v1.30.0) and configure the header content of the generated route-tree file using the `routeTreeFileHeader` field (see documentation here: https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing#options)

**Pull request closed without merging**
