### PR TITLE
docs(examples): update the vinxi-basic-ssr-streaming example to reflect the TanStack website

### PR DESCRIPTION
**Pull request by alessandrojcm**
Hey, I am playing around with vinxi and realized that the example in this repo was not working so I updated it following up with the TanStack website [migration](https://github.com/TanStack/tanstack.com/tree/tsr). Let me know if anything is wrong.

### CODE REVIEW

**Comment by SeanCassiere** [comment]
Now that Tanstack.com is using TSR in production, do you mind updating your PR here?
If everything works after the update, I'd be happy to push to this into the repo.

**Comment by alessandrojcm** [comment]
> Now that Tanstack.com is using TSR in production, do you mind updating your PR here?
> If everything works after the update, I'd be happy to push to this into the repo.

Sure I'll get to it once I get a chance

**Comment by alessandrojcm** [comment]
Done now @SeanCassiere

**Review by SeanCassiere — APPROVED** [review]

**Comment by SeanCassiere** [comment]
With CI failing, need figure out what's causing this.

**Comment by SeanCassiere** [comment]
Looks to be conflicting `vite` and `vitest` dependencies that are causing this.

**Comment by SeanCassiere** [comment]
#1467 should resolve these CI errors. Once merged in, you should be able to rebase and have CI pass.

**Comment by SeanCassiere** [comment]
@alessandrojcm When you have some time, could you update the PR and rebase with main?

The changes from #1467 should allow for the higher version of vinxi that the example was using (that required a higher vite and vitest version from our end).

**Comment by alessandrojcm** [comment]
> @alessandrojcm When you have some time, could you update the PR and rebase with main?
> 
> The changes from #1467 should allow for the higher version of vinxi that the example was using (that required a higher vite and vitest version from our end).

Done now

**Comment by SeanCassiere** [comment]
@alessandrojcm thank you!

🚀

**Pull request merged**
