### PR TITLE
refactor(react-router): support the `exactOptionalPropertyTypes` ts option in `<Link>`

### PR DESCRIPTION
**Pull request by kshramt**

### CODE REVIEW

**Comment by SeanCassiere** [comment]
https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes

**Comment by kshramt** [comment]
CI failures addressed and changes force pushed.

**Comment by schiller-manuel** [comment]
do we have runtime  tests and type tests for all those situations where you can pass in an explicit undefined?

**Comment by kshramt** [comment]
To clarify, this PR doesn't alter the type definition, but rather makes the existing behavior more explicit (see https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes ).

**Comment by schiller-manuel** [comment]
thanks for clarification.
can you please add the `exactOptionalPropertyTypes`flag to the root tsconfig.json so we catch this with our type tests?

**Comment by kshramt** [comment]
Setting `"exactOptionalPropertyTypes": true` in the root tsconfig.json will result in many type-check errors like this:

```
src/CatchBoundary.tsx:14:6 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: { getResetKey: () => string | number; children: (props: { error: Error | null; reset: () => void; }) => ReactNode; onCatch?: (error: Error, errorInfo: ErrorInfo) => void; }): CatchBoundaryImpl', gave the following error.
    Type '{ getResetKey: () => string | number; onCatch: ((error: Error, errorInfo: ErrorInfo) => void) | undefined; children: ({ error, reset }: { error: Error | null; reset: () => void; }) => string | ... 6 more ... | undefined; }' is not assignable to type 'Readonly<{ getResetKey: () => string | number; children: (props: { error: Error | null; reset: () => void; }) => ReactNode; onCatch?: (error: Error, errorInfo: ErrorInfo) => void; }>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
      Types of property 'onCatch' are incompatible.
        Type '((error: Error, errorInfo: ErrorInfo) => void) | undefined' is not assignable to type '(error: Error, errorInfo: ErrorInfo) => void'.
          Type 'undefined' is not assignable to type '(error: Error, errorInfo: ErrorInfo) => void'.
  Overload 2 of 2, '(props: { getResetKey: () => string | number; children: (props: { error: Error | null; reset: () => void; }) => ReactNode; onCatch?: (error: Error, errorInfo: ErrorInfo) => void; }, context: any): CatchBoundaryImpl', gave the following error.
    Type '{ getResetKey: () => string | number; onCatch: ((error: Error, errorInfo: ErrorInfo) => void) | undefined; children: ({ error, reset }: { error: Error | null; reset: () => void; }) => string | ... 6 more ... | undefined; }' is not assignable to type 'Readonly<{ getResetKey: () => string | number; children: (props: { error: Error | null; reset: () => void; }) => ReactNode; onCatch?: (error: Error, errorInfo: ErrorInfo) => void; }>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
      Types of property 'onCatch' are incompatible.
        Type '((error: Error, errorInfo: ErrorInfo) => void) | undefined' is not assignable to type '(error: Error, errorInfo: ErrorInfo) => void'.
          Type 'undefined' is not assignable to type '(error: Error, errorInfo: ErrorInfo) => void'.

14     <CatchBoundaryImpl
```

There are many places outside of `link.tsx` that implicitly assume `x?: T` allows `undefined`, making them incompatible with this flag.

**Comment by schiller-manuel** [comment]
would it make sense to fix all of those issues?

**Comment by kshramt** [comment]
WIP: I am trying to add the flag to `packages/react-router/tsconfig.json` (changing the root `tsconfig.json` seems a bit involved).
It seems that https://github.com/TanStack/router/blob/f36f92b459bf0aabbc4d49c1e72c8b2ad6894622/packages/react-router/src/router.ts#L707-L710 may not work well with explicit `undefined`s, as `{...{transformer: 1}, ...{transformer: undefined}}` results in `{transformer: undefined}`.

**Comment by kshramt** [comment]
Sorry, as this turned out to be more complex than I expected, I have rolled back the branch to https://github.com/TanStack/router/pull/2213/commits/7d892ac8ef96a46995b4fff31481f1cc2b6e927a . Since I've already implemented a workaround without this PR, please feel free to close it, although I believe the changes, while not comprehensive, could still be useful in some cases.

**Comment by SeanCassiere** [comment]
Closing this as there's no movement in the requirement for `exactOptionalPropertyTypes`.

**Pull request closed without merging**
