### PR TITLE
Warn against DOM-rendering elements in Wrap and InnerWrap

### PR DESCRIPTION
**Pull request by thomasballinger**

### CODE REVIEW

**Comment by thomasballinger** [comment]
Is this correct? I'm not sure if this belongs here since I see these hydration errors in Start.

**Comment by schiller-manuel** [comment]
please also update the docs

https://github.com/TanStack/router/blob/f7c74bc2d9fb8a587d300482e1d658a021792439/docs/framework/react/api/router/RouterOptionsType.md?plain=1#L192

https://github.com/TanStack/router/blob/f7c74bc2d9fb8a587d300482e1d658a021792439/docs/framework/react/api/router/RouterOptionsType.md?plain=1#L173

**Comment by thomasballinger** [comment]
ah thanks, I wrongly assumed they were autogenerated

**Comment by thomasballinger** [comment]
Are these autogenerated? I just made the change manually, I couldn't find how to generate docs if they are.

**Comment by schiller-manuel** [comment]
not autogenerated (yet 🙃)

**Pull request merged**
