### PR TITLE
fix(react-router): remove unnecessary `load` call after redirect

### LINKED ISSUE #1650: Undefined context after redirect with wrapInSuspense at root route (introduced in 1.33.6)
### Describe the bug

Undefined context after redirect with wrapInSuspense at root route.

It used to work fine in version 1.33.4.

### Your Example Website or App

https://stackblitz.com/edit/github-jr3nax-t75gmj?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

1. See the log: `context: undefined`
2. Remove `wrapInSuspense: true` and refresh
3. See the log: `context: {"test":"abc"}`

### Expected behavior

See the log: `context: {"test":"abc"}` at step 1

### Screenshots or Videos

_No response_

### Platform

- OS: macOS
- Browser: Chrome
- Version: 125.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by freshgiammi**
Possibly fixes #1650

### CODE REVIEW

**Comment by schiller-manuel** [comment]
can you add a test for this?

**Comment by freshgiammi** [comment]
@schiller-manuel I tried making a test but I'm getting some error at type level, and I also can't replicate the issue within the test itself when the patch is not applied 🤔 hitting a bit of a wall right now, you have any ideas?

**Comment by Xenfo** [comment]
Just wanted to confirm that running this PR as a patch does fix my context issues :partying_face:. Great work!

**Comment by SeanCassiere** [comment]
Tested this PR locally and it doesn't seem to address the issue mentioned in #1650.

**Comment by freshgiammi** [comment]
> Tested this PR locally and it doesn't seem to address the issue mentioned in #1650.

IIRC it did fix the issue in the reproduction template for me. However context seems to be very delicate so it might only have fixed this partially.

I should have some bandwidth to check back on this in the weekend or early next week (and redo tests based on https://github.com/TanStack/router/pull/1708).

**Comment by SeanCassiere** [comment]
@freshgiammi

If it helps, I've got a test setup in #1713 that correctly break the route context during redirection.

**Comment by SeanCassiere** [comment]
Tested these changes against the reproductions in the following issues and can confirm that this change fixes them.

- #1730
- #1670 
- #1650 
- This [comment](https://github.com/TanStack/router/issues/1656#issuecomment-2145989592) in #1656

Context-related issues still remain broken this though.

- The original reproduction in #1656

**Comment by SeanCassiere** [comment]
@freshgiammi I've applied your fixes to #1713 and it looks good! 🎉

**Comment by freshgiammi** [comment]
@SeanCassiere Great! I'll close this PR then and we can merge it via #1713 👍

**Pull request closed without merging**
