### PR TITLE
docs: fix file-based-routing.md link

### PR DESCRIPTION
**Pull request by mgcrea**
Encountered a broken link while reading the docs.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Just needs a rebase

**Comment by mgcrea** [comment]
@tannerlinsley done :)

**Comment by SeanCassiere** [comment]
Looks like this got fixed in #1189

**Comment by SeanCassiere** [comment]
Thanks for the catch @mgcrea!
I'm going ahead and closing this one as it got fixed in #1189.

**Pull request closed without merging**
