### PR TITLE
fix(react-router): decode search keys

### PR DESCRIPTION
**Pull request by kshramt**

### CODE REVIEW

**Comment by schiller-manuel** [comment]
please also add router tests. the following comes to mind: ( add more if other test make sense of course )

1. initial page load with such encoded query params
2. navigate to a route with those encoder query params

**Review by SeanCassiere — CHANGES_REQUESTED** [review]
Adding a block till @schiller-manuel comments are resolved.

**Comment by kshramt** [comment]
Thank you for the review. I have added a few tests to (hopefully) address your comments.

> please also add router tests. the following comes to mind: ( add more if other test make sense of course )
> 
>     1. initial page load with such encoded query params

https://github.com/TanStack/router/pull/2227/files#diff-d5945193f3b7ac56e5786cded7d5317ff8fa79dc819dc9f125f8a97d1dbd6aabR481

> 
>     2. navigate to a route with those encoder query params

https://github.com/TanStack/router/pull/2227/files#diff-d5945193f3b7ac56e5786cded7d5317ff8fa79dc819dc9f125f8a97d1dbd6aabR488

**Comment by schiller-manuel** [comment]
thanks a lot @kshramt for your contribution.

**Pull request merged**
