### PR TITLE
refactor(start): supply `links()` with same context signature as `meta()`

### LINKED ISSUE #2426: Similar to how `route.options.meta()` already behaves it would be nice to pass the `loaderData` and `match` to the `links()` function as well.
Similar to how `route.options.meta()` already behaves it would be nice to pass the `loaderData` and `match` to the `links()` function as well.

For my specific use-case I want to generate a `canonical` link element that is rendered via the `Meta` component inside the head. To do this I need some data from the current `match` and `loaderData`. Those are available inside `meta()` but not inside `links()`.

_Originally posted by @lo1tuma in https://github.com/TanStack/router/discussions/2419_

### PR DESCRIPTION
**Pull request by SeanCassiere**
Closes #2426

### CODE REVIEW

**Review by SeanCassiere — COMMENTED** [review]
Two things open for discussion:
1. whether we want to replicate this behaviour for `scripts`.
2. whether we want to include `matches` and `match` in the function's context like we do for `meta`.

**Comment by lo1tuma** [comment]
For `scripts()` I would appreciate to get the same information.

**Comment by SeanCassiere** [comment]
Converted back into a draft, pending a decision on the API change suggested by @rehos.

**Comment by SeanCassiere** [comment]
Closing this in favor of the new API suggested. Will push that through separately.

**Pull request closed without merging**
