### PR TITLE
remove unnecessary const

### PR DESCRIPTION
**Pull request by aprs00**
I was getting this error when trying to build my app

screenshot

### CODE REVIEW

**Comment by tannerlinsley** [comment]
What version of TypeScript are you using?

**Comment by aprs00** [comment]
> What version of TypeScript are you using?

4.9.5
https://github.com/aprs00/crypto-scanner/blob/main/package.json#L59

**Comment by aprs00** [comment]
Upgrading to typescript v5 fixed the problem

**Comment by SeanCassiere** [comment]
Closing, since a minimum TS-version of 5 is required.

https://tanstack.com/router/latest/docs/framework/react/installation#requirements

**Pull request closed without merging**
