### PR TITLE
Adding transition (concurrent) to route changes 🎉

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
This PR is heavily inspired from [new `Next js` Layout RFC](https://nextjs.org/blog/layouts-rfc).

This update would improve [Interaction on Next Paint](https://vercel.com/blog/improving-interaction-to-next-paint-with-react-18-and-suspense) and uses new concurrent feature :)

_Sorry if I made any mistakes :(_

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Could we remove all of the formatting changes?

**Comment by sanjaiyan-dev** [comment]
> Could we remove all of the formatting changes?

Yh sure, sorry

**Comment by sanjaiyan-dev** [comment]
> Could we remove all of the formatting changes?

Done :)

**Comment by sanjaiyan-dev** [comment]
> Could we remove all of the formatting changes?

Done 🙌💪

**Comment by sanjaiyan-dev** [comment]
> Could we remove all of the formatting changes?

@tannerlinsley Done 💪🙌

**Comment by tannerlinsley** [comment]
This will need to be reworked for TanStack Router. Might even be easier now?!

**Pull request closed without merging**
